#!/usr/bin/env python3
"""Generate js/uksites.js from data/uk-*.json.

The browser build has no bundler and no JSON import assertions, so the two
datasets are emitted as a plain ES module. Run calibration/fetch_uksites.py
first if the JSON needs refreshing. Everything below the generated tables is
hand-written and is carried across verbatim.
"""
import io, json

HEADER = '''// Real UK wind farm and civil radar site positions.
//
// GENERATED by calibration/build_uksites.py. Do not hand-edit; regenerate.
//
// Provenance, the accuracy test and the source cross-check are in
// calibration/UK-SITES.md. Four things matter before you use these numbers:
//
//  1. These are PLANNING RECORDS, not surveyed turbine positions. Each row is
//     one project with ONE point, taken from the UK Renewable Energy Planning
//     Database. THERE ARE NO PER-TURBINE POSITIONS HERE, for any farm. Where
//     this tool has ground truth to test against, at Kelmarsh, the recorded
//     point is 1,141 m from the true centre of the array, which is 2.4 times
//     the radius of the whole array. The coordinates are written to five
//     decimal places. That is PRECISION, NOT ACCURACY.
//  1b. The turbine COUNT, tip height and per-turbine rating do come from the
//     database, via the WINDEL July 2024 extract. They say how many machines
//     there are and how tall, not where any of them is. At Kelmarsh the count
//     is recorded as 5 where the ground truth has 6, so it is not gospel
//     either; that is n = 1.
//  2. STATUS MATTERS AND IS CARRIED HERE. Most rows are not operating plant:
//     of {n} wind records, {op} are operational and {dead} were refused,
//     withdrawn, abandoned or expired. Filter on status before drawing any
//     conclusion about what exists.
//  3. Radar positions come from two community sources that disagree with each
//     other by a median of 1.4 km, and neither is an official source.
//     No military radar is included in either source, or here.
//  4. Nothing here is suitable for a formal safeguarding assessment.

'''

LIVE = ("Operational", "Under Construction", "Awaiting Construction", "Application Submitted")

# Order fixed here, not derived from the data, so the indices written into the
# table are stable across rebuilds. Appending is safe; reordering is not.
TERRITORIES = ('England', 'Scotland', 'Wales', 'Northern Ireland',
               'Ireland', 'Isle of Man', 'Channel Islands')
DEAD_WORDS = ("Refused", "Withdrawn", "Abandoned", "Expired")

MARKER = 'const R_EARTH = 6371008.8;'


def main():
    farms = json.load(open('data/uk-wind-farms.json'))
    radars = json.load(open('data/uk-radar-sites.json'))
    tail = open('js/uksites.js').read()
    tail = tail[tail.index(MARKER):]          # hand-written helpers
    mil = open('js/uksites.js').read()
    mil = mil[mil.index('// Military air defence radar.'):mil.index(MARKER)]

    op = sum(1 for f in farms if f['status'] == 'Operational')
    dead = sum(1 for f in farms if any(w in f['status'] for w in DEAD_WORDS))

    out = io.StringIO()
    out.write(HEADER.format(n=len(farms), op=op, dead=dead))
    out.write('// Development status values, in pipeline order. The first four are what\n'
              '// "current or planned" means; the rest are projects that will not be built\n'
              '// as recorded and must be filtered out of any capacity total.\n')
    out.write('export const LIVE_STATUSES = [%s];\n\n'
              % ', '.join("'%s'" % s for s in LIVE))
    out.write('// [name, latitude, longitude, capacity_MW, status, offshore(0|1), REPD ref,\n'
              '//  turbine count|0, tip height m|0, per-turbine MW|0, grid precision m|0,\n'
              '//  territory index into TERRITORIES, or -1 for none]\n'
              '//\n'
              '// The last four come from the WINDEL July 2024 extract via\n'
              '// calibration/merge_windel.py and are 0 where that source has no figure.\n'
              '// A ZERO MEANS UNKNOWN, NOT ZERO. Tip height is the height to the blade\n'
              '// tip, not the hub. Grid precision is the coarsest round number the\n'
              "// project's British National Grid reference sits on, which is a FLOOR on\n"
              '// its uncertainty and not the uncertainty: a reference given to the metre\n'
              '// is still about a kilometre out at both sites with ground truth.\n')
    out.write('export const UK_WIND_FARMS = [\n')
    for f in farms:
        out.write('  [%s,%.5f,%.5f,%.1f,%s,%d,%s,%d,%d,%g,%d,%d],\n' % (
            json.dumps(f['name']), f['lat'], f['lon'], f['mw'],
            json.dumps(f['status']), 1 if f['offshore'] else 0, json.dumps(f['ref']),
            f.get('turbines') or 0, f.get('tipHeightM') or 0,
            f.get('turbineMw') or 0, f.get('gridPrecisionM') or 0,
            TERRITORIES.index(f['territory']) if f.get('territory') in TERRITORIES else -1))
    out.write('];\n\n')
    out.write('// The territory each site stands in, as an index, because the string\n'
              '// repeats thousands of times and the table is shipped verbatim.\n')
    out.write('export const TERRITORIES = [%s];\n\n'
              % ', '.join("'%s'" % t for t in TERRITORIES))
    out.write("// [name, role, latitude, longitude, sources, disagreement_m|0, territory|-1]\n"
              "// role: 'en-route' (NATS En Route surveillance), 'aerodrome' (airport\n"
              "// approach/terminal radar), 'unclassified' (present in one source only).\n")
    out.write('export const UK_RADAR_SITES = [\n')
    for r in radars:
        out.write('  [%s,%s,%.5f,%.5f,%s,%d,%d],\n' % (
            json.dumps(r['name']), json.dumps(r['role']), r['lat'], r['lon'],
            json.dumps(','.join(r['sources'])), r.get('source_disagreement_m') or 0,
            TERRITORIES.index(r['territory']) if r.get('territory') in TERRITORIES else -1))
    out.write('];\n\n')
    out.write(mil)
    out.write(tail)
    open('js/uksites.js', 'w').write(out.getvalue())
    print(f'js/uksites.js: {len(farms)} wind records '
          f'({sum(1 for f in farms if f["status"] in LIVE)} live), {len(radars)} radar sites')


if __name__ == '__main__':
    main()
