#!/usr/bin/env python3
"""Generate js/uksites.js from data/uk-*.json.

The browser build has no bundler and no JSON import assertions, so the two
datasets are emitted as a plain ES module. Run calibration/fetch_uksites.py
first if the JSON needs refreshing.
"""
import json, io

HEADER = '''// Real UK wind farm and civil radar site positions.
//
// GENERATED by calibration/build_uksites.py. Do not hand-edit; regenerate.
//
// Provenance, licences and the accuracy cross-check are in
// calibration/UK-SITES.md. Two things matter before you use these numbers:
//
//  1. Wind farm positions are FACILITY CENTROIDS, not turbine positions. They
//     come from the UK Renewable Energy Planning Database by way of WRI's
//     Global Power Plant Database v1.3.0 (CC BY 4.0), whose last release was
//     early 2022. The REPD's own grid references can be a kilometre out,
//     because many are recorded before the layout is fixed.
//  2. Radar positions come from two community sources that disagree with each
//     other by a median of 1.4 km and by up to 5.9 km. Neither is an official
//     source. No military radar is included in either, and none is included
//     here.
//
// Nothing in this file is suitable for a formal safeguarding assessment.

'''

def main():
    farms = json.load(open('data/uk-wind-farms.json'))
    radars = json.load(open('data/uk-radar-sites.json'))
    src = open('js/uksites.js').read()
    tail = src[src.index('];\n\n// Military air defence radar.'):]  # keep hand-written code
    out = io.StringIO()
    out.write(HEADER)
    out.write('// [name, latitude, longitude, capacity_MW, commissioning_year|0]\n')
    out.write('export const UK_WIND_FARMS = [\n')
    for f in farms:
        out.write('  [%s,%.5f,%.5f,%.1f,%d],\n'
                  % (json.dumps(f['name']), f['lat'], f['lon'], f['mw'], f['year'] or 0))
    out.write('];\n\n')
    out.write("// [name, role, latitude, longitude, sources, disagreement_m|0]\n"
              "// role: 'en-route' (NATS En Route surveillance), 'aerodrome' (airport\n"
              "// approach/terminal radar), 'unclassified' (present in one source only).\n")
    out.write('export const UK_RADAR_SITES = [\n')
    for r in radars:
        out.write('  [%s,%s,%.5f,%.5f,%s,%d],\n'
                  % (json.dumps(r['name']), json.dumps(r['role']), r['lat'], r['lon'],
                     json.dumps(','.join(r['sources'])), r.get('source_disagreement_m') or 0))
    out.write(tail)
    open('js/uksites.js', 'w').write(out.getvalue())
    print(f'js/uksites.js: {len(farms)} farms, {len(radars)} radar sites')


if __name__ == '__main__':
    main()
