// Turn data/uk-coastline.json into a JS module, so the coastline ships in the
// bundle the same way the site lists do and needs no fetch. The offline build
// is one file and cannot fetch anything, and the coastline is 82 KB, which is
// small enough to inline and far too small to be worth a separate loader.
import { readFileSync, writeFileSync } from 'node:fs';

const doc = JSON.parse(readFileSync('data/uk-coastline.json', 'utf8'));
const head = `// UK, Ireland and outlying island coastline.
//
// GENERATED by tools/build_coastline_module.mjs from data/uk-coastline.json,
// which tools/build_coastline.mjs builds from Natural Earth. Do not hand-edit.
//
// Source: ${doc.source}
// Licence: ${doc.licence}
// Built: ${doc.built}
// Includes: ${doc.includes.join(', ')}
//
// ${doc.note}
//
// Simplified with Douglas-Peucker at ${doc.simplifiedToleranceDeg} degrees, about 440 m.
// Rings smaller than ${doc.minRingAreaSqDeg} square degrees are dropped, which is about a
// quarter of a square kilometre: small enough to keep Foula and the Scillies,
// large enough to drop rocks that would be one pixel.

export const COASTLINE_SOURCE = ${JSON.stringify({
  source: doc.source, licence: doc.licence, url: doc.url, built: doc.built,
  includes: doc.includes, note: doc.note,
}, null, 2)};

/** Outer rings, each an array of [lon, lat] pairs. */
export const COASTLINE = `;
const body = '[\n' + doc.rings.map((r) => '  ' + JSON.stringify(r)).join(',\n') + '\n];\n';
writeFileSync('js/coastline.js', head + body);
const n = doc.rings.reduce((s, r) => s + r.length, 0);
console.log(`js/coastline.js: ${doc.rings.length} rings, ${n} points, `
  + `${(readFileSync('js/coastline.js').length / 1024).toFixed(0)} KB`);
